'use client';

import { useEffect, useMemo, useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Button from '@/components/ui/Button/ui';
import Input from '@/components/ui/Input/ui';
import TableCreateModal from '@/components/ui/CloudDB/TableCreateModal/ui';
import TableEditModal from '@/components/ui/CloudDB/TableEditModal/ui';
import { useCloudDbQuery } from '@/services/cloud-database/cloudDb.query';
import { useExecuteSqlMutation } from '@/services/cloud-database/cloudDb.mutation';
import { postExecuteSql } from '@/services/cloud-database/cloudDb.api';
import { SqlExecuteData } from '@/types/cloudDatabase';
import * as S from './style';

interface Props {
  projectId: string;
  cloudDbId: string;
}

interface ColumnMeta {
  name: string;
  type: string;
  isPrimary: boolean;
  isForeign: boolean;
}

type DbDialect = 'postgres' | 'mysql' | 'unknown';

const detectDialect = (image: string | undefined): DbDialect => {
  if (!image) return 'unknown';
  const lower = image.toLowerCase();
  if (lower.includes('postgres')) return 'postgres';
  if (lower.includes('mysql') || lower.includes('mariadb')) return 'mysql';
  return 'unknown';
};

const buildListTablesSql = (dialect: DbDialect) => {
  if (dialect === 'postgres') {
    return `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name`;
  }
  return `SHOW TABLES`;
};

const buildDescribeSql = (dialect: DbDialect, tableName: string) => {
  const safe = tableName.replace(/[^a-zA-Z0-9_]/g, '');
  if (dialect === 'postgres') {
    return `SELECT column_name, data_type FROM information_schema.columns WHERE table_name = '${safe}' ORDER BY ordinal_position`;
  }
  return `DESCRIBE \`${safe}\``;
};

const buildSelectAllSql = (tableName: string, limit = 100) => {
  const safe = tableName.replace(/[^a-zA-Z0-9_]/g, '');
  return `SELECT * FROM ${safe} LIMIT ${limit}`;
};

const buildCreateTableSql = (dialect: DbDialect, tableName: string, columns: Array<{
  name: string;
  type: string;
  defaultValue?: string;
  primaryKey: boolean;
  notNull: boolean;
  autoIncrement: boolean;
  unique: boolean;
  length?: string;
}>) => {
  const colDefs = columns.map((col) => {
    const parts: string[] = [`\`${col.name}\``.replace(/`/g, dialect === 'postgres' ? '"' : '`')];
    let typeStr = col.type;
    if (col.length && (typeStr === 'varchar' || typeStr === 'char' || typeStr === 'decimal')) {
      typeStr += `(${col.length})`;
    }
    parts.push(typeStr);
    if (col.primaryKey) parts.push('PRIMARY KEY');
    if (col.notNull) parts.push('NOT NULL');
    if (col.unique) parts.push('UNIQUE');
    if (col.autoIncrement) {
      parts.push(dialect === 'postgres' ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTO_INCREMENT');
    }
    if (col.defaultValue && col.defaultValue !== 'NULL' && col.defaultValue !== '') {
      parts.push(`DEFAULT ${col.defaultValue}`);
    }
    return '  ' + parts.join(' ');
  }).join(',\n');
  const quote = dialect === 'postgres' ? '"' : '`';
  return `CREATE TABLE ${quote}${tableName}${quote} (\n${colDefs}\n)`;
};

export default function TableDetailContainer({ projectId, cloudDbId }: Props) {
  const router = useRouter();
  const [activeTab, setActiveTab] = useState<'ui' | 'sql' | 'settings'>('ui');
  const [searchTerm, setSearchTerm] = useState('');
  const [openedTables, setOpenedTables] = useState<string[]>([]);
  const [activeDataTab, setActiveDataTab] = useState<string>('');
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [editingTable, setEditingTable] = useState<string>('');
  const [menuOpenTable, setMenuOpenTable] = useState<string | null>(null);

  const [tables, setTables] = useState<string[]>([]);
  const [tablesLoading, setTablesLoading] = useState(false);
  const [tablesError, setTablesError] = useState<string | null>(null);

  const [columns, setColumns] = useState<ColumnMeta[]>([]);
  const [tableData, setTableData] = useState<Array<Record<string, unknown>>>([]);
  const [tableDataLoading, setTableDataLoading] = useState(false);
  const [tableDataError, setTableDataError] = useState<string | null>(null);
  const [selectedRows, setSelectedRows] = useState<Array<unknown>>([]);

  // SQL editor tab
  const [sqlTabs, setSqlTabs] = useState<Array<{ id: number; query: string }>>([{ id: 1, query: '' }]);
  const [activeSqlTab, setActiveSqlTab] = useState<number>(1);
  const [sqlResult, setSqlResult] = useState<SqlExecuteData | null>(null);
  const [sqlError, setSqlError] = useState<string | null>(null);

  const cloudDbQuery = useCloudDbQuery(cloudDbId, projectId);
  const executeSql = useExecuteSqlMutation();

  const dialect = useMemo(
    () => detectDialect(cloudDbQuery.data?.data?.containers?.[0]?.image),
    [cloudDbQuery.data]
  );

  const dbDisplayName = cloudDbQuery.data?.data?.name ?? cloudDbId;

  const runSql = useCallback(
    async (sql: string) => {
      const response = await postExecuteSql(cloudDbId, projectId, { sql });
      return response.data?.data;
    },
    [cloudDbId, projectId]
  );

  const loadTables = useCallback(async () => {
    if (dialect === 'unknown') return;
    setTablesLoading(true);
    setTablesError(null);
    try {
      const result = await runSql(buildListTablesSql(dialect));
      const list = (result?.rows ?? []).map((row) => String(row?.[0] ?? '')).filter(Boolean);
      setTables(list);
    } catch (err) {
      setTablesError(err instanceof Error ? err.message : '테이블 목록을 불러오지 못했습니다.');
    } finally {
      setTablesLoading(false);
    }
  }, [dialect, runSql]);

  useEffect(() => {
    if (cloudDbQuery.data && dialect !== 'unknown') {
      loadTables();
    }
  }, [cloudDbQuery.data, dialect, loadTables]);

  const loadTableContent = useCallback(
    async (tableName: string) => {
      if (!tableName || dialect === 'unknown') return;
      setTableDataLoading(true);
      setTableDataError(null);
      setSelectedRows([]);
      try {
        const [descResult, selectResult] = await Promise.all([
          runSql(buildDescribeSql(dialect, tableName)),
          runSql(buildSelectAllSql(tableName)),
        ]);

        const columnMetas: ColumnMeta[] = (descResult?.rows ?? []).map((row) => {
          if (dialect === 'postgres') {
            return {
              name: String(row?.[0] ?? ''),
              type: String(row?.[1] ?? ''),
              isPrimary: false,
              isForeign: false,
            };
          }
          return {
            name: String(row?.[0] ?? ''),
            type: String(row?.[1] ?? ''),
            isPrimary: String(row?.[3] ?? '').toUpperCase() === 'PRI',
            isForeign: false,
          };
        });
        setColumns(columnMetas);

        const cols = selectResult?.columns ?? [];
        const rows = (selectResult?.rows ?? []).map((row) => {
          const obj: Record<string, unknown> = {};
          cols.forEach((c, i) => { obj[c] = row?.[i]; });
          return obj;
        });
        setTableData(rows);
      } catch (err) {
        setTableDataError(err instanceof Error ? err.message : '테이블 데이터를 불러오지 못했습니다.');
        setColumns([]);
        setTableData([]);
      } finally {
        setTableDataLoading(false);
      }
    },
    [dialect, runSql]
  );

  useEffect(() => {
    if (activeDataTab) {
      loadTableContent(activeDataTab);
    }
  }, [activeDataTab, loadTableContent]);

  const handleBack = () => {
    router.push(`/project/manage/${projectId}`);
  };

  const handleTableClick = (tableName: string) => {
    if (!openedTables.includes(tableName)) {
      setOpenedTables([...openedTables, tableName]);
    }
    setActiveDataTab(tableName);
  };

  const closeTableTab = (tableName: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const newOpened = openedTables.filter((t) => t !== tableName);
    setOpenedTables(newOpened);
    if (activeDataTab === tableName) {
      setActiveDataTab(newOpened[0] ?? '');
    }
  };

  const handleDeleteTable = async (tableName: string) => {
    if (!window.confirm(`'${tableName}' 테이블을 삭제할까요? 모든 데이터가 사라집니다.`)) return;
    try {
      const safe = tableName.replace(/[^a-zA-Z0-9_]/g, '');
      await runSql(`DROP TABLE ${safe}`);
      setOpenedTables((prev) => prev.filter((t) => t !== tableName));
      if (activeDataTab === tableName) setActiveDataTab('');
      await loadTables();
    } catch (err) {
      alert(err instanceof Error ? err.message : '테이블 삭제에 실패했습니다.');
    }
  };

  const handleCreateTableSubmit = async (data: { tableName: string; description: string; columns: Array<{
    name: string; type: string; defaultValue: string; primaryKey: boolean; notNull: boolean; autoIncrement: boolean; unique: boolean;
  }> }) => {
    try {
      const sql = buildCreateTableSql(dialect, data.tableName, data.columns);
      await runSql(sql);
      setIsCreateModalOpen(false);
      await loadTables();
      handleTableClick(data.tableName);
    } catch (err) {
      alert(err instanceof Error ? err.message : '테이블 생성에 실패했습니다.');
    }
  };

  const handleEditTableSubmit = async (data: { tableName: string }) => {
    if (!editingTable || data.tableName === editingTable) {
      setIsEditModalOpen(false);
      return;
    }
    try {
      const safeOld = editingTable.replace(/[^a-zA-Z0-9_]/g, '');
      const safeNew = data.tableName.replace(/[^a-zA-Z0-9_]/g, '');
      const sql = dialect === 'postgres'
        ? `ALTER TABLE "${safeOld}" RENAME TO "${safeNew}"`
        : `ALTER TABLE \`${safeOld}\` RENAME TO \`${safeNew}\``;
      await runSql(sql);
      setIsEditModalOpen(false);
      setOpenedTables((prev) => prev.map((t) => (t === editingTable ? data.tableName : t)));
      if (activeDataTab === editingTable) setActiveDataTab(data.tableName);
      await loadTables();
    } catch (err) {
      alert(err instanceof Error ? err.message : '테이블 수정에 실패했습니다.');
    }
  };

  const handleAddValue = async () => {
    if (!activeDataTab) return;
    const json = window.prompt('추가할 행을 JSON으로 입력해주세요. 예: {"name": "abc", "age": 20}');
    if (!json) return;
    try {
      const parsed = JSON.parse(json) as Record<string, unknown>;
      const cols = Object.keys(parsed);
      if (cols.length === 0) return;
      const safe = activeDataTab.replace(/[^a-zA-Z0-9_]/g, '');
      const colList = cols.map((c) => (dialect === 'postgres' ? `"${c}"` : `\`${c}\``)).join(', ');
      const valList = cols.map((c) => {
        const v = parsed[c];
        if (v === null) return 'NULL';
        if (typeof v === 'number' || typeof v === 'boolean') return String(v);
        return `'${String(v).replace(/'/g, "''")}'`;
      }).join(', ');
      await runSql(`INSERT INTO ${safe} (${colList}) VALUES (${valList})`);
      await loadTableContent(activeDataTab);
    } catch (err) {
      alert(err instanceof Error ? err.message : '행 추가에 실패했습니다.');
    }
  };

  const handleDeleteRows = async () => {
    if (selectedRows.length === 0 || !activeDataTab) return;
    const pkCol = columns.find((c) => c.isPrimary)?.name ?? 'id';
    if (!columns.some((c) => c.name === pkCol)) {
      alert(`기본 키(${pkCol})를 찾을 수 없습니다. SQL 편집기를 사용해주세요.`);
      return;
    }
    if (!window.confirm(`${selectedRows.length}개의 행을 삭제할까요?`)) return;
    try {
      const safe = activeDataTab.replace(/[^a-zA-Z0-9_]/g, '');
      const ids = selectedRows.map((v) =>
        typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`
      ).join(', ');
      const colQuoted = dialect === 'postgres' ? `"${pkCol}"` : `\`${pkCol}\``;
      await runSql(`DELETE FROM ${safe} WHERE ${colQuoted} IN (${ids})`);
      setSelectedRows([]);
      await loadTableContent(activeDataTab);
    } catch (err) {
      alert(err instanceof Error ? err.message : '행 삭제에 실패했습니다.');
    }
  };

  const toggleAllRows = (checked: boolean) => {
    const pkCol = columns.find((c) => c.isPrimary)?.name ?? 'id';
    if (checked) {
      setSelectedRows(tableData.map((row) => row[pkCol]).filter((v) => v !== undefined));
    } else {
      setSelectedRows([]);
    }
  };

  const toggleRow = (value: unknown) => {
    setSelectedRows((prev) =>
      prev.includes(value) ? prev.filter((v) => v !== value) : [...prev, value]
    );
  };

  const filteredTables = tables.filter((t) => t.toLowerCase().includes(searchTerm.toLowerCase()));

  const handleSqlExecute = async () => {
    const current = sqlTabs.find((t) => t.id === activeSqlTab);
    if (!current?.query.trim()) return;
    setSqlError(null);
    try {
      const result = await runSql(current.query);
      setSqlResult(result ?? null);
    } catch (err) {
      setSqlError(err instanceof Error ? err.message : 'SQL 실행에 실패했습니다.');
      setSqlResult(null);
    }
  };

  const updateActiveSqlQuery = (value: string) => {
    setSqlTabs((prev) => prev.map((t) => (t.id === activeSqlTab ? { ...t, query: value } : t)));
  };

  const addSqlTab = () => {
    const newId = sqlTabs.length === 0 ? 1 : Math.max(...sqlTabs.map((t) => t.id)) + 1;
    setSqlTabs([...sqlTabs, { id: newId, query: '' }]);
    setActiveSqlTab(newId);
  };

  const closeSqlTab = (id: number, e: React.MouseEvent) => {
    e.stopPropagation();
    const next = sqlTabs.filter((t) => t.id !== id);
    if (next.length === 0) {
      setSqlTabs([{ id: 1, query: '' }]);
      setActiveSqlTab(1);
      return;
    }
    setSqlTabs(next);
    if (activeSqlTab === id) setActiveSqlTab(next[0].id);
  };

  const currentSqlQuery = sqlTabs.find((t) => t.id === activeSqlTab)?.query ?? '';

  const highlightSql = (sql: string) => {
    const keywords = /\b(SELECT|FROM|WHERE|INSERT|UPDATE|DELETE|CREATE|DROP|ALTER|TABLE|INTO|VALUES|SET|JOIN|LEFT|RIGHT|INNER|OUTER|ON|AND|OR|NOT|IN|LIKE|ORDER|BY|GROUP|HAVING|LIMIT|OFFSET|AS|DISTINCT|COUNT|SUM|AVG|MAX|MIN|UNION|ALL|EXISTS|BETWEEN|IS|NULL|DESC|ASC|DESCRIBE)\b/gi;
    return sql.replace(keywords, (match) => `<span style="color: #0366d6; font-weight: 600;">${match}</span>`);
  };

  return (
    <>
      <S.Container>
        <S.Header>
          <S.Title>{dbDisplayName}</S.Title>
        </S.Header>

        <S.TabContainer>
          <S.Tab $active={activeTab === 'ui'} onClick={() => setActiveTab('ui')}>
            테이블 UI
          </S.Tab>
          <S.Tab $active={activeTab === 'sql'} onClick={() => setActiveTab('sql')}>
            SQL 쿼리
          </S.Tab>
          <S.Tab $active={activeTab === 'settings'} onClick={() => setActiveTab('settings')}>
            설정
          </S.Tab>
        </S.TabContainer>

        {activeTab === 'ui' && (
          <S.ContentWrapper>
            <S.Sidebar>
              <S.SidebarHeader>
                <Button variant="confirm" onClick={() => setIsCreateModalOpen(true)} disabled={dialect === 'unknown'}>
                  새 테이블
                </Button>
              </S.SidebarHeader>

              <S.SearchWrapper>
                <Input
                  placeholder="테이블 검색"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                />
              </S.SearchWrapper>

              <S.TableList>
                {tablesLoading && <S.EmptyMessage>불러오는 중...</S.EmptyMessage>}
                {tablesError && <S.EmptyMessage>{tablesError}</S.EmptyMessage>}
                {!tablesLoading && !tablesError && dialect === 'unknown' && (
                  <S.EmptyMessage>지원되지 않는 DB 타입입니다.</S.EmptyMessage>
                )}
                {!tablesLoading && !tablesError && dialect !== 'unknown' && filteredTables.length === 0 && (
                  <S.EmptyMessage>테이블이 없습니다.</S.EmptyMessage>
                )}
                {filteredTables.map((tableName) => (
                  <S.TableItemWrapper key={tableName}>
                    <S.TableItem
                      $selected={activeDataTab === tableName}
                      onClick={() => handleTableClick(tableName)}
                    >
                      <S.TableIcon />
                      <S.TableName>{tableName}</S.TableName>
                      <S.TableMenu
                        onClick={(e) => {
                          e.stopPropagation();
                          setMenuOpenTable(menuOpenTable === tableName ? null : tableName);
                        }}
                      >
                        ⋮
                      </S.TableMenu>
                    </S.TableItem>
                    {menuOpenTable === tableName && (
                      <S.TableDropdown>
                        <S.DropdownItem
                          onClick={() => {
                            setEditingTable(tableName);
                            setIsEditModalOpen(true);
                            setMenuOpenTable(null);
                          }}
                        >
                          이름 변경
                        </S.DropdownItem>
                        <S.DropdownItem
                          $danger
                          onClick={() => {
                            setMenuOpenTable(null);
                            handleDeleteTable(tableName);
                          }}
                        >
                          삭제
                        </S.DropdownItem>
                      </S.TableDropdown>
                    )}
                  </S.TableItemWrapper>
                ))}
              </S.TableList>

              <S.SidebarActions />
            </S.Sidebar>

            <S.MainContent>
              <S.DataTabContainer>
                {openedTables.map((tableName) => (
                  <S.DataTab
                    key={tableName}
                    $active={activeDataTab === tableName}
                    onClick={() => setActiveDataTab(tableName)}
                  >
                    <S.DataTabIcon />
                    {tableName}
                    <S.CloseTab onClick={(e) => closeTableTab(tableName, e)}>×</S.CloseTab>
                  </S.DataTab>
                ))}
              </S.DataTabContainer>

              <S.ActionBar>
                <Button variant="confirm" onClick={handleAddValue} disabled={!activeDataTab}>값 추가</Button>
                {selectedRows.length > 0 && (
                  <Button variant="cancel" onClick={handleDeleteRows}>
                    선택 행 삭제 ({selectedRows.length})
                  </Button>
                )}
              </S.ActionBar>

              {!activeDataTab && (
                <S.EmptyMessage>왼쪽에서 테이블을 선택해주세요.</S.EmptyMessage>
              )}

              {activeDataTab && tableDataLoading && <S.EmptyMessage>불러오는 중...</S.EmptyMessage>}
              {activeDataTab && tableDataError && <S.EmptyMessage>{tableDataError}</S.EmptyMessage>}

              {activeDataTab && !tableDataLoading && !tableDataError && (
                <S.TableWrapper>
                  <S.Table>
                    <S.TableHead>
                      <S.TableRow>
                        <S.CheckboxCell>
                          <input
                            type="checkbox"
                            checked={selectedRows.length === tableData.length && tableData.length > 0}
                            onChange={(e) => toggleAllRows(e.target.checked)}
                          />
                        </S.CheckboxCell>
                        {columns.map((column) => (
                          <S.TableHeaderCell key={column.name}>
                            <S.ColumnHeader>
                              {column.isPrimary && (
                                <S.KeyIcon src="/icons/cloud-db/primary.svg" alt="Primary Key" />
                              )}
                              {column.isForeign && (
                                <S.KeyIcon src="/icons/cloud-db/foreign.svg" alt="Foreign Key" />
                              )}
                              {column.name} <S.SortIcon>{column.type}</S.SortIcon>
                            </S.ColumnHeader>
                          </S.TableHeaderCell>
                        ))}
                      </S.TableRow>
                    </S.TableHead>
                    <S.TableBody>
                      {tableData.map((row, idx) => {
                        const pkCol = columns.find((c) => c.isPrimary)?.name ?? 'id';
                        const pkVal = row[pkCol];
                        return (
                          <S.TableRow key={idx}>
                            <S.CheckboxCell>
                              <input
                                type="checkbox"
                                checked={pkVal !== undefined && selectedRows.includes(pkVal)}
                                onChange={() => pkVal !== undefined && toggleRow(pkVal)}
                              />
                            </S.CheckboxCell>
                            {columns.map((column) => (
                              <S.TableCell key={column.name}>
                                {row[column.name] === null || row[column.name] === undefined
                                  ? ''
                                  : String(row[column.name])}
                              </S.TableCell>
                            ))}
                          </S.TableRow>
                        );
                      })}
                    </S.TableBody>
                  </S.Table>
                </S.TableWrapper>
              )}
            </S.MainContent>
          </S.ContentWrapper>
        )}

        {activeTab === 'sql' && (
          <S.SqlContainer>
            <S.SqlTabContainer>
              {sqlTabs.map((query) => (
                <S.SqlTab
                  key={query.id}
                  $active={activeSqlTab === query.id}
                  onClick={() => setActiveSqlTab(query.id)}
                >
                  <S.SqlTabIcon />#{query.id}
                  <S.SqlTabClose onClick={(e) => closeSqlTab(query.id, e)}>×</S.SqlTabClose>
                </S.SqlTab>
              ))}
              <S.SqlTabAdd onClick={addSqlTab}>+</S.SqlTabAdd>
            </S.SqlTabContainer>

            <S.SqlEditor>
              <S.SqlLineNumbers>
                {currentSqlQuery.split('\n').map((_, idx) => (
                  <S.SqlLineNumber key={idx}>{idx + 1}</S.SqlLineNumber>
                ))}
              </S.SqlLineNumbers>
              <S.SqlEditorWrapper>
                <S.SqlHighlight dangerouslySetInnerHTML={{ __html: highlightSql(currentSqlQuery) }} />
                <S.SqlTextarea
                  value={currentSqlQuery}
                  onChange={(e) => updateActiveSqlQuery(e.target.value)}
                  placeholder="SQL 쿼리를 입력하세요"
                  spellCheck={false}
                />
              </S.SqlEditorWrapper>
            </S.SqlEditor>

            <S.SqlResultSection>
              <S.SqlResultHeader>
                <S.SqlResultTitle>
                  결과
                  {sqlResult && (
                    <span style={{ marginLeft: '1rem', fontSize: '0.875rem', color: '#6B6B6B', fontWeight: 400 }}>
                      {sqlResult.affected_rows} rows · {sqlResult.execution_time_ms}ms
                    </span>
                  )}
                </S.SqlResultTitle>
                <Button
                  variant="confirm"
                  size="small"
                  onClick={handleSqlExecute}
                  disabled={executeSql.isPending}
                >
                  {executeSql.isPending ? '실행 중...' : '실행'}
                </Button>
              </S.SqlResultHeader>

              {sqlError && <S.EmptyMessage>{sqlError}</S.EmptyMessage>}

              {sqlResult && (
                <S.TableWrapper>
                  <S.Table>
                    <S.TableHead>
                      <S.TableRow>
                        {sqlResult.columns.map((col) => (
                          <S.TableHeaderCell key={col}>{col}</S.TableHeaderCell>
                        ))}
                      </S.TableRow>
                    </S.TableHead>
                    <S.TableBody>
                      {sqlResult.rows.map((row, idx) => (
                        <S.TableRow key={idx}>
                          {sqlResult.columns.map((_, ci) => (
                            <S.TableCell key={ci}>
                              {row?.[ci] === null || row?.[ci] === undefined ? '' : String(row[ci])}
                            </S.TableCell>
                          ))}
                        </S.TableRow>
                      ))}
                    </S.TableBody>
                  </S.Table>
                </S.TableWrapper>
              )}
            </S.SqlResultSection>
          </S.SqlContainer>
        )}

        {activeTab === 'settings' && (
          <S.ContentWrapper>
            <div style={{ padding: '2rem' }}>
              <h3>데이터베이스 정보</h3>
              {cloudDbQuery.isPending && <p>불러오는 중...</p>}
              {cloudDbQuery.data && (
                <div style={{ display: 'grid', gap: '0.5rem', maxWidth: 600 }}>
                  <div><strong>이름:</strong> {cloudDbQuery.data.data.name}</div>
                  <div><strong>네임스페이스:</strong> {cloudDbQuery.data.data.namespace}</div>
                  <div><strong>레플리카:</strong> {cloudDbQuery.data.data.status?.ready_replicas ?? 0} / {cloudDbQuery.data.data.replicas}</div>
                  <div><strong>이미지:</strong> {cloudDbQuery.data.data.containers?.[0]?.image ?? '-'}</div>
                  <div>
                    <strong>PVC:</strong>
                    <ul>
                      {cloudDbQuery.data.data.pvcs?.map((pvc) => (
                        <li key={pvc.name}>{pvc.name} · {pvc.size} · {pvc.phase}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}
            </div>
          </S.ContentWrapper>
        )}
      </S.Container>

      <TableCreateModal
        isOpen={isCreateModalOpen}
        onClose={() => setIsCreateModalOpen(false)}
        onSubmit={handleCreateTableSubmit}
      />

      <TableEditModal
        isOpen={isEditModalOpen}
        onClose={() => {
          setIsEditModalOpen(false);
          setEditingTable('');
        }}
        tableName={editingTable}
        onSubmit={handleEditTableSubmit}
      />
    </>
  );
}
